name: Sync with Upstream

on:
#   schedule:
#     #- cron: "0 0 * * *" #every 24 hours
#     - cron: "*/5 * * * *"
    repository_dispatch:

jobs:
#  sync-upstream-master:
#    runs-on: [ubuntu-latest]
#    steps:
#    - uses: actions/checkout@master  
#    - name: repo-sync
#      uses: repo-sync/github-sync@v2
#      with:
#        source_repo: "https://github.com/SecureAuthCorp/impacket.git"
#        source_branch: "master"
#        destination_branch: "upstream_master"
#        github_token: ${{ secrets.GITHUB_TOKEN }}
 
 merge-upstream-master:
   runs-on: [ubuntu-latest]
   steps:
#      - uses: actions/checkout@master
     - name: Test hub
       run: which hub
     - name: Clone repo
       run: |
         git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

     - name: Merge Upstream Master
       working-directory: ./impacket_static_binaries
       run: |
         git remote add upstream https://github.com/SecureAuthCorp/impacket.git
         git fetch upstream
         git merge --no-ff --no-commit upstream/master
         git reset HEAD README.md .github #never change these
         git checkout -- README.md .github
         git commit -m "merged upstream/master"
         git push origin master
         
         
         
