name: Sync with Upstream

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
 repo-sync:
   runs-on: [ubuntu-latest]
   steps:
   - uses: actions/checkout@master  
   - name: repo-sync
     uses: repo-sync/github-sync@v2
     with:
       source_repo: "https://github.com/SecureAuthCorp/impacket.git"
       source_branch: "master"
       destination_branch: "upstream_master"
       github_token: ${{ secrets.GITHUB_TOKEN }}
